config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'tasks#index'
    resources :tasks, except: [:show]
    resources :users, except: [:show] do
      get :task
    end

    get 'sign_up', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

  resources :tasks, path: "mission_possible" do
    collection do
      get :list
    end
  end

  resources :users, only: [:create] do
    collection do
      get :sign_up
      get :sign_in
    end
  end

  resources :categories, only: [:index]

  post "/users/sign_in", to: "sessions#create", as: "login"
	delete "/users", to: "sessions#destroy", as: "logout"

  root "users#sign_in"

  # API
	# POST /api/v1/tasks/2/favorite
	namespace :api do
		namespace :v1 do
			resources :tasks, only: [] do
				member do
					post :favorite
				end
			end
		end
	end
end

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="row align-items-start">
    <div class="col-w">
      <%= image_tag 'logo.fw.png' %>
    </div>
    <div class="col-w" style="text-align:right">
      <%= link_to t('hp') , list_tasks_path %> |
      <% if user_signed_in? %>
        <%= link_to t('nav_logout') , logout_path, method: "delete" %>
        <mark><%= current_user.user_name %><%= t('nav_task') %></mark> |
      <% else %>
        <%= link_to t('nav_login') , sign_in_users_path %> |
        <%= link_to t('nav_signup') , sign_up_users_path %> |
      <% end %>
      <%= link_to "中文版" , :controller=> controller_name, :action => action_name, :locale => "zh-TW" %> |
      <%= link_to "English" , :controller=> controller_name, :action => action_name, :locale => "en" %>
    </div>
  </div>
</div>