config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'tasks#index'
    resources :tasks, except: [:show]
    resources :users, except: [:show] do
      get :task
    end

    get 'sign_up', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

  resources :tasks, path: "mission_possible" do
    collection do
      get :list
    end
  end

  resources :users, only: [:create] do
    collection do
      get :sign_up
      get :sign_in
    end
  end

  resources :categories, only: [:index]

  post "/users/sign_in", to: "sessions#create", as: "login"
	delete "/users", to: "sessions#destroy", as: "logout"

  root "users#sign_in"

  # API
	# POST /api/v1/tasks/2/favorite
	namespace :api do
		namespace :v1 do
			resources :tasks, only: [] do
				member do
					post :favorite
				end
			end
		end
	end
end

app/models/user.rb
require 'digest'

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true, length: { minimum: 4 }, presence: true
  validates :user_name, presence: true, uniqueness: true
  has_many :tasks, dependent: :destroy
  has_many :bookmarks
  has_many :favorite_notes,
            through: :bookmarks,
            source: :task

  before_create :encrypt_password

  def favorite?(n)
    favorite_notes.exists?(n.id)
  end

private
  def encrypt_password
    salted_pw = "eiojre#{self.password}rewropwr"
    self.password = Digest::SHA1.hexdigest(salted_pw)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  #  the order of before_action matters here
  before_action :find_user, only:[:edit,:show, :update, :destroy, :task]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "#{@user.user_name} 已註冊成功！"
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: '更新帳戶成功'
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user != current_user
      if @user.destroy
        redirect_to admin_users_path, notice: '刪除帳戶成功'
      else
        redirect_to admin_users_path, notice: @user.errors.full_messages.to_sentence
      end
    else
      if @user.destroy
        session[:user_id] = nil
        redirect_to admin_users_path, notice: '刪除帳戶成功'
      else
        redirect_to admin_users_path, notice: @user.errors.full_messages.to_sentence
      end
    end
  end

  # 取得使用者的所有任務
  def task
    @q = @user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page params[:page]
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_up
    @user = User.new
  end

  def sign_in
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
        redirect_to list_tasks_path
    else
        render :sign_up
    end
  end

  def profile
  end

  private
    def user_params
      params.require(:user).permit(:user_name, :password, :password_confirmation, :email)
    end 

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1>
  <%= "後臺任務數量" %>： <%= "使用者列表" %>
</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <td><%= "使用者名稱" %></td>
      <td><%= "電子信箱" %></td>
      <td><%= "角色" %></td>
      <td><%= "任務數量" %></td>
      <td><%= "操作" %></td>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user.user_name, task_admin_user_path(user) %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user_role(user.admin) %>
        <td>
          <%= user.tasks.count %>
        </td>
        <%# 顯示使用者的任務數量 %>
          <td>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "編輯", edit_admin_user_path(user) , class: 'dropdown-item' %>
                <div class="dropdown-divider"></div>
                <%= link_to "查看", admin_user_path(user) , class: 'dropdown-item' %>
                  <div class="dropdown-divider"></div>
                  <%= link_to t"刪除", admin_user_path(user) , class: 'dropdown-item' , method: 'delete' ,
                    data: { confirm: "確認刪除嗎？" }%>
            </div>
          </td>
      </tr>
      <% end %>

  </tbody>
</table>

<%= button_to t("users.create"), admin_sign_up_path ,class:"btn btn-outline-dark", method: "get" %>